---
# the SBT installer needs curl
- name: Install curl
  apt: pkg=curl update_cache=yes

- name: Download SBT
  get_url: url=http://dl.bintray.com/sbt/debian/sbt-0.13.2.deb
           dest=/tmp/sbt.deb

- name: Install SBT
  shell: dpkg -i /tmp/sbt.deb
