---
- hosts: development
  sudo: yes
  sudo_user: ${dev_user}
  tasks:
  - name: Check Emacs installation
    register: emacs_installed
    shell: emacs --version | grep 24.3
    ignore_errors: True

  - include: "tasks/install-emacs.yml"
    when: emacs_installed|failed

  - include: "tasks/configure-emacs.yml"
