---
- name: Copy .vimrc
  copy: src=../files/.vimrc
        dest=/home/{{dev_user}}/.vimrc

- name: Create the colors dir
  file: path=/home/{{dev_user}}/.vim/colors
        state=directory

- name: Copy molokai
  copy: src=../files/colors/molokai.vim
        dest=/home/{{dev_user}}/.vim/colors/molokai.vim

- name: Copy FreshCut
  copy: src=../files/colors/FreshCut.vim
        dest=/home/{{dev_user}}/.vim/colors/FreshCut.vim

- name: Create vim bundle dir
  file: path=/home/{{dev_user}}/.vim/bundle
        state=directory

- name: Blindly execute pathogen install script
  shell: mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

- name: Install plugins
  git:  repo={{ item.address }}
        dest=/home/{{dev_user}}/.vim/bundle/{{item.name}}
        depth=1
  with_items:
    - { name: 'tabular'          , address: 'https://github.com/godlygeek/tabular.git' }
    - { name: 'vim-fugitive'     , address: 'https://github.com/tpope/vim-fugitive.git' }
