- name: Copy .emacs
  copy: src=../files/.emacs
        dest=/home/vagrant/.emacs

- name: Create .emacs.d
  file: path=/home/vagrant/.emacs.d
        state=directory

- name: Copy .emacs.d/package-installation.el
  copy: src=../files/.emacs.d/package-installation.el
        dest=/home/vagrant/.emacs.d/package-installation.el

- name: Copy .emacs.d/move-mode.el
  copy: src=../files/.emacs.d/move-mode.el
        dest=/home/vagrant/.emacs.d/move-mode.el

- name: Copy .emacs.d/haskell.el
  copy: src=../files/.emacs.d/haskell.el
        dest=/home/vagrant/.emacs.d/haskell.el
