- name: install libncurses
  sudo: yes
  sudo_user: root
  apt: pkg=libncurses5-dev

- name: Download emacs 24
  get_url: url=http://ftp.heanet.ie/mirrors/gnu/emacs/emacs-24.3.tar.gz
           dest=/tmp/emacs-install.tar.gz

- name: Unzip emacs
  shell: tar xzf /tmp/emacs-install.tar.gz
         chdir=/tmp
         creates=/tmp/emacs-24.3

- name: Configure emacs
  shell: ./configure --with-xpm=no --with-jpeg=no --with-gif=no --with-tiff=no
         chdir=/tmp/emacs-24.3

- name: Make emacs
  shell: make
         chdir=/tmp/emacs-24.3

- name: Install emacs
  sudo: yes
  sudo_user: root
  shell: make install
         chdir=/tmp/emacs-24.3
