---
- hosts: development
  sudo: yes
  tasks:

  # Play
  - name: Check play installation
    shell: play | grep -q 2.1.4
    register: play_installed
    ignore_errors: yes
  - include: "tasks/install-play.yml"
    when: play_installed|failed
