---
- name: Download Play 2.1.4
  get_url: url=http://downloads.typesafe.com/play/2.1.4/play-2.1.4.zip
           dest=/tmp/play.zip

- name: Install unzip
  apt: update_cache=yes pkg=$item
  with_items:
  - zip
  - unzip

- name: Unzip Play
  shell: unzip /tmp/play.zip > /dev/null
         chdir=/tmp
         creates=/tmp/play-2.1.4

- name: Create /home/${dev_user}/bin
  file: path=/home/${dev_user}/bin
        state=directory
        owner=${dev_user}
        group=${dev_user}

- name: Copy Play
  shell: export DIR=/home/${dev_user}/bin/play-2.1.4; cp -R /tmp/play-2.1.4 $DIR && chown -R ${dev_user}:${dev_user} $DIR
         creates=/home/${dev_user}/bin/play-2.1.4

- name: Check Play in PATH
  shell: grep -q '/home/${dev_user}/bin/play-2.1.4:$PATH' /home/${dev_user}/.bashrc
  register: play_in_path
  ignore_errors: yes

- name: Add Play to PATH
  shell: echo 'export PATH=/home/${dev_user}/bin/play-2.1.4:$PATH' >> /home/${dev_user}/.bashrc
  when: play_in_path|failed
