- name: install GHC dependencies
  sudo: yes
  sudo_user: root
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - build-essential
    - libgmp-dev
    - libffi-dev
    - libbsd-dev
    - libc6-dev
    - libc6
    - libffi6
    - libgmp10
    - libtinfo5
    - zlib1g-dev

- name: Download GHC 7.8.2
  get_url: url=http://www.haskell.org/ghc/dist/7.8.2/ghc-7.8.2-x86_64-unknown-linux-deb7.tar.xz
           dest=/tmp/ghc-install.tar.xz

- name: Unzip GHC
  shell: tar xJf /tmp/ghc-install.tar.xz
         chdir=/tmp
         creates=/tmp/ghc-7.8.2

- name: Configure GHC
  shell: ./configure
         chdir=/tmp/ghc-7.8.2

- name: Install GHC
  sudo_user: root
  shell: make install
         chdir=/tmp/ghc-7.8.2
