---
- hosts: development
  sudo: yes
  tasks:
    - name: Install a bunch of common tools
      apt: update_cache=yes pkg={{item}} state=latest
      with_items:
        - autoconf
        - automake
        - build-essential
        - curl
        - wget
        - git-core
        - tree
        - unzip
        - tmux
    - name: Configure Tmux
      remote_user: dev_user
      copy: src=files/.tmux.conf
            dest=/home/{{dev_user}}/.tmux.conf
